# Generated by Django 3.2 on 2023-02-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='owner',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='owner',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='invites',
            old_name='owner',
            new_name='userId',
        ),
    ]
